<?php
include '../smit/Backend/db.php';
session_start();
$uname = $_SESSION['username'];
$order_id = $_SESSION['order_id'];
$api_key = "rzp_test_lPJcw5eOhf3stK";

$stmt = $pdo->prepare("select * from `tbl_order_details` where `order_id` = :order_id");
$stmt->bindParam(':order_id', $order_id);
$stmt->execute();
$result = $stmt->fetch(PDO::FETCH_ASSOC);

$amount = $result['price'];

$stmt = $pdo->prepare("select * from `tbl_customer_details` where `name` = :a");
$stmt->bindParam(':a', $uname);
$stmt->execute();
$result = $stmt->fetch(PDO::FETCH_ASSOC);

$email = $result['email'];
$contactno = $result['contactno'];
?>

<form action="/smit/payment_success.php" method="POST">
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="<?php echo $api_key; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="<?php echo $amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
        data-currency="INR" // You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
        data-buttontext="Pay with Razorpay"
        data-name="vision shop"
        data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
        data-image="https://example.com/your_logo.jpg"
        data-prefill.name="<?php echo $uname; ?>"
        data-prefill.email="<?php echo $email; ?>"
        data-prefill.contact="<?php echo $contactno; ?>"
        data-theme.color="#F37254"></script>
    <input type="hidden" custom="Hidden Element" name="hidden" />
</form>
<!-- data-order_id="<?php echo $order_id; ?>"// Replace with the order_id generated by you in the backend.  -->